site_name: MAPS Academy design hands-on training

nav:
  - Introduction: index.md
  - SkyWater technology:
      - Overview: pdk/sky130.md
      - Process:  pdk/process.md
  - Labs:
      - Setup: 
        - For a new installation: labs/lab01.md
        - From a previous installation: labs/lab08.md
      - Ideal models:
        - Ideal Operational Amplifier: labs/lab02.md
        - Ideal Charge Sensitive Amplifier: labs/lab03.md
        - Ideal CSA with feedback resistor: labs/lab04.md
      - Transistor based:
        - Transistor design of a simple CSA Amplifier: labs/lab05.md
        - Full CSA simulation: labs/lab06.md
        - Layout of the CSA Amplifier: labs/lab07.md
  - Lectures:
    - Semiconductor ecosystem: lectures/lecture01.md
    - CMOS process fabrication: lectures/lecture02.md
    - Microelectronics design concepts: lectures/lecture03.md

theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.tracking
    - navigation.instant
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy

extra_css:
  - stylesheets/extra.css

plugins:
  - glightbox:
      skip_classes:
        - skip-lightbox

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
