site_name: MAPS Academy design hands-on training

nav:
  - Introduction: index.md
  - SkyWater technology:
      - Overview: pdk/sky130.md
      - Process:  pdk/process.md
  - Labs:
      - Setup: labs/lab01.md
      - Ideal Operational Amplifier: labs/lab02.md
      - Ideal Charge Sensitive Amplifier: labs/lab03.md
  - Lectures:
    - Lecture 01: lectures/lecture01.md

theme:
  name: material
  logo: images/logo-mapsacademy.png
  palette:
    primary: 'indigo'
    accent: 'indigo'
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.tracking
    - navigation.instant
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
